# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Invoice\UserInterface\Http\CustomerController:
        class: App\Invoice\UserInterface\Http\CustomerController
        public: true

    App\Invoice\Application\CommandHandler\AddInvoiceHandler:
        tags: [{ name: messenger.message_handler, bus: messenger.bus.commands}]

    App\Invoice\Application\CommandHandler\AddPaymentHandler:
        tags: [{ name: messenger.message_handler, bus: messenger.bus.commands}]

    App\Invoice\Application\CommandHandler\AddCustomerHandler:
        tags: [ { name: messenger.message_handler, bus: messenger.bus.commands } ]

    App\Invoice\Application\QueryHandler\GetAccountSummaryHandler:
        tags: [ { name: messenger.message_handler, bus: messenger.bus.queries } ]